(function(g){var window=this;'use strict';var wsb=function(a,b){g.V.call(this,{I:"button",Ma:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],Y:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",Y:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",Y:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",Y:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",Y:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.Ra("click",this.onClick,this);this.updateValue("title",g.CU(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.AU(b.Ne(),this.element))},xsb=function(a){g.V.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.rh);this.T(a,"onStateChange",this.n2)},ysb=function(a){g.YV.call(this,a);
this.B=new g.hL(this);this.j=new xsb(this.player);this.j.hide();g.KU(this.player,this.j.element,4);a.hg()&&(this.load(),g.ov(a.getRootNode(),"ytp-player-minimized",!0))};
g.w(wsb,g.V);wsb.prototype.onClick=function(){this.J.ib("onExpandMiniplayer")};g.w(xsb,g.V);g.k=xsb.prototype;
g.k.show=function(){this.j=new g.av(this.l2,null,this);this.j.start();if(!this.G){this.tooltip=new g.jY(this.player,this);g.M(this,this.tooltip);g.KU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Td=new g.BW(this.player);g.M(this,this.Td);this.B=new g.V({I:"div",S:"ytp-miniplayer-scrim"});g.M(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.QS);var a=new g.V({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.JG()]});g.M(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.PS);a=new wsb(this.player,this);g.M(this,a);a.Ja(this.B.element);this.C=new g.V({I:"div",S:"ytp-miniplayer-controls"});g.M(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.QS);var b=new g.V({I:"div",S:"ytp-miniplayer-button-container"});g.M(this,b);b.Ja(this.C.element);a=new g.V({I:"div",S:"ytp-miniplayer-play-button-container"});g.M(this,a);a.Ja(this.C.element);var c=new g.V({I:"div",S:"ytp-miniplayer-button-container"});
g.M(this,c);c.Ja(this.C.element);this.N=new g.xX(this.player,this,!1);g.M(this,this.N);this.N.Ja(b.element);b=new g.wX(this.player,this);g.M(this,b);b.Ja(a.element);this.nextButton=new g.xX(this.player,this,!0);g.M(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.cY(this.player,this);g.M(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.CX(this.player,this);g.M(this,this.progressBar);g.KU(this.player,this.progressBar.element,4);this.D=new g.V({I:"div",S:"ytp-miniplayer-buttons"});
g.M(this,this.D);g.KU(this.player,this.D.element,4);a=new g.V({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.JG()]});g.M(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.PS);a=new g.V({I:"button",Ma:["ytp-miniplayer-replay-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.iwa()]});g.M(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.F$);this.T(this.player,"presentingplayerstatechange",this.m2);this.T(this.player,"appresize",this.Yb);
this.T(this.player,"fullscreentoggled",this.Yb);this.Yb();this.G=!0}0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.hide.call(this);this.player.hg()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.xa.call(this)};
g.k.PS=function(){this.player.stopVideo();this.player.ib("onCloseMiniplayer")};
g.k.F$=function(){this.player.playVideo()};
g.k.QS=function(a){if(a.target===this.B.element||a.target===this.C.element)g.$L(this.player.Ub())?this.player.pauseVideo():this.player.playVideo()};
g.k.rh=function(){g.ov(this.player.getRootNode(),"ytp-player-minimized",this.player.hg())};
g.k.Wf=function(){this.progressBar.Mc();this.K.Mc()};
g.k.l2=function(){this.Wf();this.j&&this.j.start()};
g.k.m2=function(a){g.kH(a.state,32)&&this.tooltip.hide()};
g.k.Yb=function(){g.Q_a(this.progressBar,0,this.player.rb().getPlayerSize().width,!1);g.DX(this.progressBar)};
g.k.n2=function(a){this.player.hg()&&(0===a?this.hide():this.show())};
g.k.Ne=function(){return this.tooltip};
g.k.Lt=function(a,b,c,d,e){var f=0,h=d=0,l=g.Ds(a);if(b){c=g.jv(b,"ytp-prev-button")||g.jv(b,"ytp-next-button");var m=g.jv(b,"ytp-play-button"),n=g.jv(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Bs(b,this.element),h=b.x,f=b.y-12):n&&(h=g.jv(b,"ytp-miniplayer-button-top-left"),f=g.Bs(b,this.element),b=g.Ds(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.rb().getPlayerSize().width;e=f+(e||0);l=g.xe(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.w(ysb,g.YV);g.k=ysb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.ov(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.YV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.rl=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.XV("miniplayer",ysb);})(_yt_player);
